### ISSUE TITLE
Zoom in/out doesn't stop

### ISSUE THREAD

**Issue by Vincent-NB** [bitfocus/companion-module-axis-ptz#2]
After using the zoom in/out action PTZ STOP doesn't stop it.
Camera: AXIS V5915

**Comment by fbosman** [comment]
Hi, what version of Companion are you using? This issue had been solved in the latest version of this module for my axis camera. Can you try the latest beta companion?

**Comment by Vincent-NB** [comment]
I'm on version 2.2.0. Both on PC and a Raspberry Pi.

**Comment by fbosman** [comment]
I'm running on 2.2.0+3953-beta-531fde4 on an axis Q6045-E-MKII (the only one available for test) and it runs ok.
I'll see what I can do

**Comment by Vincent-NB** [comment]
It could very well be a problem with this specific camera. I'm also having trouble sending HTTP commands from companion.

**Comment by fbosman** [comment]
Is there any line in the log?

**Comment by fbosman** [comment]
Is this still an issue? I'm working on version 2 with autofocus setting and feedbacks
